name: Deploy to GitHub Pages

on:
  # Déclenche l'action à chaque "push" (envoi de code) sur la branche principale
  push:
    branches: ["main"]
  # Permet aussi de lancer le déploiement manuellement depuis l'onglet "Actions"
  workflow_dispatch:

# Autorisations nécessaires pour que le bot GitHub puisse publier ton site
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # Dossier racine contenant ton index.htmlt  
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4